# Generated by Django 4.2 on 2023-05-01 17:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='پیام'),
        ),
        migrations.AddField(
            model_name='posts',
            name='discription',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن مقاله '),
        ),
    ]
