# Generated by Django 4.2 on 2023-05-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contact_message_posts_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='Image_person/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone_number',
            field=models.IntegerField(verbose_name='شماره تلفن'),
        ),
    ]
