# Generated by Django 4.2 on 2023-05-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': 'رضایت نامه ها'},
        ),
        migrations.AlterModelTable(
            name='testimonial',
            table='Testimonial',
        ),
    ]
