# Generated by Django 4.2 on 2023-05-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_testimonial_options_alter_testimonial_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام دسته بندی سازمانی ')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی سمت اعضا ',
                'db_table': 'Category_Person',
            },
        ),
    ]
