# Generated by Django 4.2 on 2023-05-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_posts_self_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='picture1',
            field=models.FileField(blank=True, null=True, upload_to='Article_picture/', verbose_name='عکس سر تیتر '),
        ),
        migrations.AddField(
            model_name='posts',
            name='picture2',
            field=models.FileField(blank=True, null=True, upload_to='Article_picture/', verbose_name='عکس سر تیتر '),
        ),
        migrations.AddField(
            model_name='posts',
            name='picture3',
            field=models.FileField(blank=True, null=True, upload_to='Article_picture/', verbose_name='عکس سر تیتر '),
        ),
    ]
