# Generated by Django 4.2 on 2023-05-02 13:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_posts_picture1_alter_posts_picture2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله ')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس مقاله ')),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن پیام')),
                ('time_created', models.DateField(default=django.utils.timezone.now, verbose_name='زمان ساخته شدن ')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شود ')], max_length=1, verbose_name='وضعیت')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.members', verbose_name='نویسنده')),
            ],
        ),
    ]
