# Generated by Django 4.2 on 2023-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blogs_options_alter_blogs_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
