# Generated by Django 4.2 on 2023-05-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_blogs_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_for_Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام دسته بندی ')),
            ],
            options={
                'verbose_name_plural': ' دسته بندی های مقالات و محتوا ساخته شده ',
                'db_table': 'Category_for_Blogs',
            },
        ),
    ]
