# Generated by Django 4.2 on 2023-05-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_category_for_blogs_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.category_for_blogs'),
        ),
    ]
