# Generated by Django 4.2 on 2023-05-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blogs_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='head_picture',
            field=models.FileField(blank=True, null=True, upload_to='Articles_Blogs', verbose_name='عکس مقاله یا نظریات '),
        ),
    ]
