# Generated by Django 4.2 on 2023-05-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_members_discription_of_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_in_Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام عنوان ')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('picture', models.FileField(upload_to='Work_in_Building', verbose_name='عکس عنوان')),
            ],
            options={
                'verbose_name_plural': 'کار های صورت گرفته برای تمایش صفحه اول سایت',
                'db_table': 'Work_in_Building',
            },
        ),
    ]
