# Generated by Django 4.2 on 2023-05-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_work_in_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_in_building',
            name='description',
            field=models.TextField(max_length=200, verbose_name='توضیحات'),
        ),
    ]
