# Generated by Django 4.2 on 2023-05-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_work_in_building_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_in_building',
            name='status',
            field=models.BooleanField(default=False, verbose_name='نمایش داده شود '),
        ),
    ]
