# Generated by Django 4.2 on 2023-05-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_work_in_building_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_in_building',
            name='description',
            field=models.CharField(max_length=200, verbose_name='توضیحات'),
        ),
    ]
