# Generated by Django 4.2 on 2023-05-03 07:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_work_in_building_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات در مورد خدمت '),
        ),
        migrations.AddField(
            model_name='service_category',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='Services/', verbose_name='عکس خدمت'),
        ),
        migrations.AlterField(
            model_name='service_category',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='آدرس خدمت '),
        ),
    ]
