# Generated by Django 4.2 on 2023-05-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_service_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='status',
            field=models.BooleanField(default=False, verbose_name='منتشر شود '),
        ),
    ]
